Repository helm/helm-2to3, pull requests merged in 2019-12, with the labels that each got.

#100 fix(config): Plugin symbolic links
  pkg/common/utils.go
  pkg/v3/utils.go
Labels: bug, size/L

#99 Add batch process command
  README.md
Labels: documentation, size/S

#102 v2.0.1, fix plugin symbolic links, support helm v3.0.1
  go.mod
  go.sum
  plugin.yaml
Labels: size/XS

#104 keep file permission when moving config
  pkg/common/utils.go
Labels: size/XS
