Repository helm/helm-2to3, pull requests merged in 2019-09, with the labels that each got.

#9 Upgrade to Helm v3.0.0-beta
  Makefile
  go.mod
  go.sum
  pkg/v3/release.go
Labels: bug

#10 Add support for Tiller out of cluster
  README.md
  cmd/convert.go
  cmd/root.go
  main.go
  pkg/v2/release.go
  pkg/v3/connect.go
Labels: enhancement

#25 use helm org
  .circleci/config.yml
  README.md
  plugin.yaml
  scripts/install_plugin.sh
Labels: size/S

#33 Add clean up capability
  README.md
  cmd/cleanup.go
  cmd/convert.go
  cmd/environment.go
  cmd/move_config.go
  cmd/root.go
  go.mod
  pkg/common/utils.go
  pkg/v2/release.go
  pkg/v2/utils.go
  pkg/v3/utils.go
  plugin.yaml
Labels: enhancement, size/XL

#34 Fix plugin description
  plugin.yaml
Labels: size/XS

#35 Add pre-migration section to README
  README.md
Labels: documentation, size/M

#37 Add dry run option to move config
  README.md
  cmd/cleanup.go
  cmd/environment.go
  cmd/move_config.go
  pkg/common/utils.go
Labels: enhancement, size/L

#39 Add details about multiple clusters and Tiller
  README.md
Labels: documentation, size/S

#41 Update operation flow
  README.md
  cmd/cleanup.go
  cmd/move_config.go
  pkg/common/utils.go
Labels: enhancement, size/S

#42 Update plugin to v0.1.3
  plugin.yaml
Labels: size/XS

#44 Delete Kubernetes Tiller service object
  cmd/cleanup.go
  pkg/v2/utils.go
Labels: bug, size/M

#47 Update README.md
  README.md
Labels: size/XS

#48 Readme update
  README.md
Labels: size/S

#50 Update README for better clarification on clean up
  README.md
Labels: documentation, size/S

#51 Update removal message after convert
  cmd/convert.go
Labels: enhancement, size/XS

#53 Enable cleanup on a per functional basis
  README.md
  cmd/cleanup.go
  cmd/environment.go
Labels: enhancement, size/M

#54 Remove CLI settings from cmd exported functions
  cmd/cleanup.go
  cmd/convert.go
Labels: bug, size/L
