Repository helm/helm-2to3, pull requests merged in 2019-10, with the labels that each got.

#56 Update README with post configuration migration steps
  README.md
Labels: documentation, size/M

#57 Add cross platform file path
  pkg/common/utils.go
  pkg/v2/utils.go
Labels: enhancement, size/M

#58 Add logger
  cmd/cleanup.go
  cmd/convert.go
  cmd/move_config.go
  pkg/common/utils.go
  pkg/v2/release.go
  pkg/v2/utils.go
Labels: enhancement, size/L

#59 Add capability to limit v2 release versions migrated
  README.md
  cmd/convert.go
Labels: enhancement, size/M

#61 Update warning message to correspond to the cleanup flags set
  cmd/cleanup.go
Labels: bug, size/S

#62 Fix the check to see if create directory succeeded
  .gitignore
  pkg/common/utils.go
Labels: bug, size/XS

#63 Update readme to explain cluster access
  README.md
Labels: documentation, size/XS

#65 Upgrade to Helm v3 Beta 4
  go.mod
  go.sum
  pkg/v3/connect.go
  pkg/v3/release.go
  pkg/v3/utils.go
Labels: enhancement, size/XL

#66 Upgrade to release 0.1.4
  plugin.yaml
Labels: size/XS

#68 Update some v3 release object properties
  pkg/v3/release.go
Labels: size/M

#69 Upgrade to Helm 3 Beta 5 and Helm 2.15.1
  go.mod
  go.sum
  pkg/v3/connect.go
  pkg/v3/release.go
  plugin.yaml
Labels: enhancement, size/L

#73 Upgrade to Helm 3 RC1 and Helm 2.15.2
  go.mod
  go.sum
  pkg/v3/connect.go
  plugin.yaml
Labels: enhancement, size/L

#74 Add arm64 build support
  .goreleaser.yml
  scripts/install_plugin.sh
Labels: enhancement, size/XS

#78 fix(*): update gopath to use github.com/helm convention
  README.md
  cmd/cleanup.go
  cmd/convert.go
  cmd/environment.go
  cmd/move_config.go
  go.mod
  main.go
  pkg/common/utils.go
Labels: size/M

#81 ref(cleanup): use strings.Builder
  cmd/cleanup.go
  pkg/common/utils.go
Labels: size/S

#82 Plugin v0.1.7
  plugin.yaml
Labels: size/XS
