Repository helm/helm-2to3, pull requests merged in 2019-11, with the labels that each got.

#85 Upgrade to Helm 3 RC2
  go.mod
  go.sum
  plugin.yaml
Labels: size/XS

#87 Upgrade to Helm 3 RC3
  go.mod
  go.sum
  plugin.yaml
Labels: size/S

#89 fix(convert): Release versions not migrated in latest release order
  cmd/convert.go
  pkg/v2/release.go
Labels: bug, size/M

#90 chore(*): Bump plugin to the next release version
  plugin.yaml
Labels: size/XS

#92 chore(*): Bump Helm 3 module to released version
  go.mod
  go.sum
  plugin.yaml
Labels: size/S
