Repository helm/helm-2to3, pull requests merged in 2020-02, with the labels that each got.

#116 feat(*) : Add support for passing kube config path and kube context
  README.md
  cmd/cleanup.go
  cmd/convert.go
  cmd/environment.go
  cmd/move_config.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/utils/utils.go
  pkg/v2/release.go
  pkg/v3/connect.go
  pkg/v3/release.go
Labels: enhancement, size/XL

#117 chore(*): Cut a new release
  README.md
  plugin.yaml
Labels: size/S

#118 Steps to install on Windows
  README.md
Labels: documentation, size/XS

#120 fix(typo): Fix "configration" typos in command.
  cmd/move_config.go
Labels: size/XS

#121 Fixed plugin install command documentation
  README.md
Labels: size/XS

#124 Update helm-plugin-utils module
  go.mod
  go.sum
  plugin.yaml
Labels: bug, size/XS
