Repository helm/helm-2to3, pull requests merged in 2020-03, with the labels that each got.

#129 Read kube-context from environment variable
  cmd/root.go
Labels: bug, size/S

#127 Provide a completion file for static completion
  .goreleaser.yml
  completion.yaml
  plugin.yaml
  scripts/install_plugin.sh
Labels: enhancement, size/M

#131 Add scripts/install_plugin.sh to archive
  .goreleaser.yml
  plugin.yaml
  scripts/install_plugin.sh
Labels: bug, size/XS

#132 feat(cleanup): Cleanup of a release
  README.md
  cmd/cleanup.go
  completion.yaml
  plugin.yaml
Labels: enhancement, size/M

#140 fix(convert): Hook events which are being mapped incorrectly
  pkg/v3/release.go
  plugin.yaml
Labels: bug, size/M
